export { Header } from "./Header";
export { Invite } from "./main/Invite";
export { Timer } from "./main/Timer";
export { Info } from "./main/Info";
export { FirstImage } from "./main/FirstImage";
export { Footer } from "./Footer";
export { TextFirst } from "./main/TextFirst";
export { InfoSecond } from "./main/InfoSecond";
export { TextSecond } from "./main/TextSecond";
